Aephy.WEB/Controllers/LandingPageController.cs
using Aephy.WEB.Models;
using Aephy.WEB.Provider;
using Azure.Storage.Blobs;
using Azure.Storage.Sas;
using Azure.Storage;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using static System.Net.Mime.MediaTypeNames;
using System.Reflection;
using Microsoft.AspNetCore.Http;
using Aephy.Helper.Helpers;
using System.Net.Mail;
using Org.BouncyCastle.Math.EC.Endo;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Stripe;

namespace Aephy.WEB.Controllers
{
    public class LandingPageController : Controller
    {
        private readonly IApiRepository _apiRepository;
        private const string ContainerName = "cvfiles";
        private const string ImageContainerName = "profileimages";
        private const string customSolutionContainer = "customsolutionfiles";
        private readonly IConfiguration _configuration;
        private readonly string _connectionString;
        private readonly string _rootPath;

        public LandingPageController(IConfiguration configuration, IApiRepository apiRepository, IWebHostEnvironment hostEnvironment)
        {
            _apiRepository = apiRepository;
            _configuration = configuration;
            _connectionString = configuration.GetConnectionString("AzureBlobStorage");
            _rootPath = hostEnvironment.WebRootPath;
            _connectionString = "DefaultEndpointsProtocol=https;AccountName=aephystorageaccount;AccountKey=nEy6xh4P4m2d94iDgqq+yNB99bucjGMD1wp2L6sbsNFjHPaUQiCHgc5b4hmBmeRtYsiA/WvudVmV+AStwz3djw==;EndpointSuffix=core.windows.net";
        }
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Industries()
        {
            return View();
        }

        public ActionResult Services()
        {
            return View();
        }

        public ActionResult WhyAephy()
        {
            return View();
        }

        public ActionResult GigOpenings()
        {
            return View();
        }

        public ActionResult OpenGigRoles()
        {
            return View();
        }

        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult Careers()
        {
            return View();
        }

        public ActionResult CareerOpenRoles()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult PostYourRequest()
        {
            return View();
        }

        public ActionResult BrowseSolutions()
        {

            return View();
        }

        /*        [HttpGet]
                public ActionResult Project()
                {
                    return View();
                }
        */
        [HttpGet]
        public ActionResult Project(int? Service, int? Solution, int? Industry)
        {
            ViewData["Solution"] = Solution;
            ViewData["Industry"] = Industry;
            ViewData["Service"] = Service;

            return View();
        }

        [HttpGet]
        public int BusinessDaysUntil(DateTime firstDay, DateTime lastDay, DateTime[]? bankHolidays) //,DateTime[]? bankHolidays
        {
            firstDay = firstDay.Date;
            lastDay = lastDay.Date;
            int days = 0;

            for (DateTime date = firstDay; date <= lastDay; date = date.AddDays(1))
            {
                if (firstDay.DayOfWeek != DayOfWeek.Saturday && firstDay.DayOfWeek != DayOfWeek.Sunday && !bankHolidays.Contains(date)) // && !bankHolidays.Contains(date)
                {
                    days++;
                }
                firstDay = firstDay.AddDays(1);
            }

            return days;
        }

        [HttpPost]
        public async Task<string> SaveClientAvailability([FromBody] ClientAvailabilityModel model)
        {
            string userType = HttpContext.Session.GetString("LoggedUserRole");
            string clientID = HttpContext.Session.GetString("LoggedUser");

            if (!string.IsNullOrEmpty(userType) && userType == "Client" && !string.IsNullOrEmpty(clientID))
            {
                model.ClientId = clientID.ToString();
            }
            else
            {
                model.ClientId = null;
            }
            string holidaysList = model.HolidaysList;
            DateTime firstDay = model.StartDate != null ? Convert.ToDateTime(model.StartDate) : DateTime.Now;
            DateTime lastDay = model.EndDate != null ? Convert.ToDateTime(model.EndDate) : DateTime.Now;
            DateTime[] holidays = new DateTime[0];
            var response = string.Empty;
            if (holidaysList != null && holidaysList != "")
            {
                var holidaysLst = holidaysList.Split(';');
                holidays = holidaysLst.Select(x => DateTime.Parse(x)).ToArray();
            }
            model.Holidays = holidays;
            if (firstDay < lastDay)
            {
                response = await _apiRepository.MakeApiCallAsync("api/Client/saveClientAvailabilityData", HttpMethod.Post, model);
            }
            return response;
        }

        [HttpPost]
        public async Task<string> SaveRequestedProposal(IFormFile httpPostedFileBase, string SolutionData)
        {
            try
            {
                IFormFile CustomSolutionFile = httpPostedFileBase;
                var result = JsonConvert.DeserializeObject<CustomSolutionsModel>(SolutionData);


                string userType = HttpContext.Session.GetString("LoggedUserRole");
                string clientID = HttpContext.Session.GetString("LoggedUser");

                if (!string.IsNullOrEmpty(userType) && userType == "Client" && !string.IsNullOrEmpty(clientID))
                {
                    result.ClientId = clientID;
                }
                var response = await _apiRepository.MakeApiCallAsync("api/Client/SaveRequestedProposal", HttpMethod.Post, result);

                dynamic data = JsonConvert.DeserializeObject(response);

                //return response;
                if (data.Message == "Submitted Successfully")
                {
                    if (result.AlreadyExistDocument)
                    {
                        int Id = data.Result;
                        CustomSolutionDocument customSolution = new CustomSolutionDocument();
                        customSolution.AlreadyExistDocument = true;
                        customSolution.ID = Id;
                        //opengigroles.FreelancerId = freelancer;
                        var ok = await _apiRepository.MakeApiCallAsync("api/Client/UpdateSolutionDocument", HttpMethod.Post, customSolution);
                        return response;
                    }
                    else
                    {
                        if (data != null)
                        {

                            int Id = data.Result;
                            var d = await UploadSolutionDocument(CustomSolutionFile, Id);
                            var ok = await _apiRepository.MakeApiCallAsync("api/Client/UpdateSolutionDocument", HttpMethod.Post, d);
                            dynamic UploadResponse = JsonConvert.DeserializeObject(ok);
                            if (UploadResponse != null)
                            {
                                return ok;
                            }
                            else
                            {
                                return "Failed to submit your Request !";
                            }
                        }
                    }
                }
                else
                {
                    return response;
                }
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
            return "Failed to submit your Request !";
        }

        public ActionResult FAQ()
        {
            return View();
        }

        [HttpGet]
        public async Task<string> GetRolesList()
        {
            var RolesList = await _apiRepository.MakeApiCallAsync("api/Admin/ActiveRolesList", HttpMethod.Get);
            return RolesList;
        }

        [HttpPost]
        public async Task<string> ApplyForOpenGigRoles(IFormFile httpPostedFileBase, string GigOpenRolesData)
        {
            try
            {

                IFormFile CVFile = httpPostedFileBase;
                var result = JsonConvert.DeserializeObject<OpenGigRolesModel>(GigOpenRolesData);


                var freelancer = HttpContext.Session.GetString("LoggedUser");
                result.FreelancerID = freelancer;
                var currentDateTime = DateTime.Now;
                result.CreatedDateTime = currentDateTime;
                var openGigRolesData = await _apiRepository.MakeApiCallAsync("api/Freelancer/OpenGigRolesApply", HttpMethod.Post, result);
                dynamic data = JsonConvert.DeserializeObject(openGigRolesData);
                if (data != null)
                {
                    if (data.Message == "Applied Successfully")
                    {
                        int Id = data.Result;
                        var d = await SaveCVFile(CVFile, Id);
                        var ok = await _apiRepository.MakeApiCallAsync("api/Freelancer/UpdateCV", HttpMethod.Post, d);
                        dynamic ImageResponse = JsonConvert.DeserializeObject(ok);
                        if (ImageResponse != null)
                        {
                            return ImageResponse.Message;
                        }
                        else
                        {
                            return "Failed to Apply !";
                        }
                    }
                    else
                    {
                        return data.Message;
                    }
                }
            }
            catch (Exception ex)
            {

Aephy.WEB/Views/LandingPage/AboutUs.cshtml
@{
    ViewData["Title"] = "About us";
    Layout = "~/Views/Shared/_LandingPageLayout.cshtml";
}

<link href="../assets/css/aboutusstylesheet.css" rel="stylesheet" />

<main id="main" class="main cls-fixed-common">
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero d-flex align-items-center">
        <div class="container">
            <!--Row 1-->
            <div class="row d-flex justify-content-center first-row">
                <div class="col-lg-6 order-3 order-lg-1 d-flex flex-column justify-content-center" style="justify-content:center;">
                    <h2 data-aos="fade-up" class="service-title-size">
                        About Us
                    </h2>
                    <div class="gy-2 mt-2" data-aos="fade-up" data-aos-delay="400" style="text-align:center;">
                        <p class="section-title-size">
                            Committed to transforming your business with top-tier, affordable AI services.
                        </p>
                    </div>
                </div>

                <div class="col-lg-1 order-2 order-lg-2">
                </div>

                <div class="col-lg-5 order-1 order-lg-3 hero-img" data-aos="zoom-out">
                    <img src="~/assets/img/about/about us/about_us_v2.svg" class="img-fluid mb-3 mb-lg-0" alt="About Us" />

                </div>
            </div>
        </div>
    </section><!-- End Hero Section -->

    <section id="JoinUs" class="JoinUs pt-0">
        <div class="container" data-aos="fade-up">
            @*<div class="section-header">
            <hr />
            <h3 class="justify-content-start align-items-center"><label style="background-color:#fff; padding:0 1.3em 0 1.3em;">How</label></h3>
            </div>*@

            <!--Row 2 Join Us-->
            <div class="row justify-content-center" style="padding:40px 0;">
                <div class="col-lg-12 px-lg-5">
                    <div class="title">
                        <label>
                            Ephylink is on a Mission to Empower Businesses with Cutting-Edge AI Services that Deliver Real-World Results
                        </label>
                    </div>
                    <div class="description">
                        <p>
                            Founded in 2023 by Dimitrios Vamvakas, MSc in economics, Ephylink is a dedicated platform that offers cutting-edge AI solutions to businesses, provided by exceptional freelancers. We are passionate about enabling businesses of all sizes to leverage the power of AI and achieve their goals.
                            <br /><br />
                            Through our extensive network of AI experts, we provide a diverse range of AI projects tailored to meet the unique needs of different industries. Our freelancers specialize in key areas such as AI strategy and consulting, AI engineering, data science and analytics, and AI operations. This ensures that we have the expertise to deliver high-quality solutions that drive business success.
                            <br /><br />
                            At Ephylink, we believe in the power of collaboration. We promote close client collaboration within our network to gain a comprehensive understanding of your specific requirements and objectives. This collaborative approach allows our freelancers to create customized AI projects that align perfectly with your vision, ensuring maximum impact and value for your business.
                            <br /><br />
                            We take immense pride in the transformative impact our AI projects have had on businesses. Our network of specialists has consistently helped streamline operations, optimize processes, and enhance customer experiences, empowering businesses to stay ahead in today's competitive landscape.
                            <br /><br />
                            Join our platform today and unlock the full potential of AI projects provided by our talented freelancers. Experience the innovation, expertise, and exceptional results that AI can bring to your business, propelling you to new heights of success.
                            <br /><br />
                            We look forward to partnering with you on your AI journey.
                        </p>
                    </div>
                    <div class="content">
                        <div class="image">
                            <img src="~/assets/img/about/founder-ceo_image.jpg" />
                        </div>
                        <div class="info">
                            <div class="name">Dimitris Vamvakas</div>
                            <div class="role">
                                <label>Founder & CEO</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row gy-4" style="padding:50px 0;">
                <div class="col-lg-5 position-relative align-self-center order-lg-first order-first">
                    <div style="text-align:center;">
                        <img src="~/assets/img/join-us_blue.svg" class="img-fluid" alt="" />
                    </div>
                </div>
                <div class="col-lg-7 content order-last order-lg-last d-block" style="position:relative; justify-content:center; align-items:center;">
                    @{
                        if (Context.Session.GetString("LoggedUser") != null)
                        {
                            <div style="text-align:center;">
                                <a class="btn btn-brand ms-lg-3 m-4" href="~/Home/Dashboard">Dashboard</a>
                            </div>
                        }
                        else
                        {
                            <div style="text-align:center;">
                                <h3>
                                    Join Us
                                </h3>
                            </div>
                            <div style="text-align:center;">
                                <a class="btn btn-brand ms-lg-3 m-4" href="~/Home/Login">Login</a>
                                <a class="btn btn-brand ms-lg-3 m-4" href="~/Home/Register">Sign Up</a>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </section>
</main>

Aephy.WEB/Views/LandingPage/CheckoutCancel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<main id="main" class="main">
    <div class="text-center">
        <h1 class="display-4">Thank you</h1>
        <p id="cancel-msg"></p>
    </div>
</main>

<script>
    $(function () {
        GetUserCancelCheckoutDetails()
    })

    function GetUserCancelCheckoutDetails() {
        $("#preloader").show();
        var urlParams = new URLSearchParams(window.location.search);
        var contractId = urlParams.get('cntId');
        var data = {
            Id: contractId
        }

        $.ajax({
            type: "POST",
            url: "@Url.Action("GetUserCancelCheckoutDetails", "LandingPage")",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                $("#cancel-msg").html(result.Message)
                $("#preloader").hide();
            },
            error: function (result) {
                showToaster("error", "Error !", result.responseText);
                $("#preloader").hide();
            }
        });
        //window.location = "@Url.Action("GetUserStripeDetails", "Home")";
    }
</script>

Aephy.WEB/Views/LandingPage/CheckoutSuccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<main id="main" class="main">
    <div class="text-center">
        <h1 class="display-4">Thank you</h1>
        <p id="sucess-msg"></p>
    </div>
</main>

<script>
    $(function () {
        GetUserSuccessCheckoutDetails()
    })

    function GetUserSuccessCheckoutDetails() {
        $("#preloader").show();

         var urlParams = new URLSearchParams(window.location.search);
        var contractId = urlParams.get('cntId');
           var data ={
                Id : contractId
           }

        $.ajax({
            type: "POST",
            url: "@Url.Action("GetUserSuccessCheckoutDetails", "LandingPage")",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: JSON.stringify(data),
            success: function (result) {
                $("#sucess-msg").html(result.Message)
                $("#preloader").hide();
            },
            error: function (result) {
                showToaster("error", "Error !", result.responseText);
                $("#preloader").hide();
            }
        });
        //window.location = "@Url.Action("GetUserStripeDetails", "Home")";
    }
</script>

Aephy.WEB/Views/LandingPage/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_LandingPageLayout.cshtml";
}
<link href="../assets/css/contactstylesheet.css" rel="stylesheet" />
<main class="main cls-fixed-common" id="main">
    <!-- ======= Contact Us Section ======= -->
    <section id="AlwaysEvolving" class="AlwaysEvolving">
        <div class="container px-lg-5 px-2">
            <div class="section-header">
            @*<span>Why us</span>*@
            <h2>Contact Us</h2>
            </div>
            <div class="row justify-content-center first-row" style="background-color: #f5f5f5;">
                <div class="col-lg-5 col-12 content order-last" style="position: relative;display: grid;justify-content:center;align-items:center;">
                    <img src="~/assets/img/about/careers/contact_us_blue.svg" class=" img-fluid" alt="">
                </div>
                <div class="col-lg-7 col-12 order-first py-5">
                    <h3 data-aos="fade-up">
                        Inquiries
                    </h3>
                    <a href="mailto:contact@ephylink.com">contact@ephylink.com</a>
                </div>
            </div>

            <div class="row justify-content-center first-row mt-5">
                <div class="col-lg-6 content order-lg-first order-last">
                    @*<div class="map">
                        <div class="map-responsive">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d50310.605369180805!2d23.69713963922665!3d37.990830014198835!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14a1bd1f067043f1%3A0x2736354576668ddd!2sAthens%2C%20Greece!5e0!3m2!1sen!2sin!4v1687934701128!5m2!1sen!2sin" width="400" height="400" style="border:0;width:100%;" allowfullscreen loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>*@
                    <img src="~/assets/img/about/careers/address.svg" class="img-fluid" alt="" />
                </div>
                <div class="col-lg-6 order-lg-last order-first d-flex flex-column my-3">
                    <h3 data-aos="fade-up">
                        Our Office
                    </h3>
                    <div class="my-2 d-grid">
                        <a style="color: gray;">
                            Ephylink,
                        </a>
                        <a style="color: gray;">
                            Aristofanous 5, Patras, Greece,
                        </a>
                        <a style="color: gray;">
                            26500
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>