Aephy.WEB.Admin/Controllers/SolutionsController.cs
using Aephy.WEB.Admin.Models;
using Aephy.WEB.Provider;
using Azure.Core.Pipeline;
using Azure.Storage;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Sas;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Diagnostics.Metrics;
using System.Reflection.Metadata;
using System.Text.RegularExpressions;
using static Azure.Core.HttpHeader;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Aephy.WEB.Admin.Controllers
{
    public class SolutionsController : Controller
    {
        private readonly IApiRepository _apiRepository;
        private const string ContainerName = "profileimages";
        private readonly IConfiguration _configuration;
        private readonly string _connectionString;

        public SolutionsController(IConfiguration configuration, IApiRepository apiRepository)
        {
            _apiRepository = apiRepository;
            _configuration = configuration;
            _connectionString = configuration.GetConnectionString("AzureBlobStorage");
            _connectionString = "DefaultEndpointsProtocol=https;AccountName=aephystorageaccount;AccountKey=nEy6xh4P4m2d94iDgqq+yNB99bucjGMD1wp2L6sbsNFjHPaUQiCHgc5b4hmBmeRtYsiA/WvudVmV+AStwz3djw==;EndpointSuffix=core.windows.net";
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DescribeSolution()
        {
            return View();
        }
        [HttpPost]
        public async Task<string> AddorEditSolution(IFormFile httpPostedFileBase, string SolutionData)
        {
            try
            {
                var result = JsonConvert.DeserializeObject<SolutionsModel>(SolutionData);
                IFormFile imageFile = httpPostedFileBase;

                var solutionData = await _apiRepository.MakeApiCallAsync("api/Admin/AddorEditSolutionData", HttpMethod.Post, result);
                if (solutionData != "")
                {
                    dynamic data = JsonConvert.DeserializeObject(solutionData);
                    if (data["StatusCode"] == 200)
                    {
                        if (result.Id == 0)
                        {

                            int Id = data.Result;
                            var fileData = await SaveImageFile(imageFile, Id);
                            await _apiRepository.MakeApiCallAsync("api/Admin/UpdateImage", HttpMethod.Post, fileData);

                        }
                        else
                        {
                            if (imageFile != null)
                            {
                                int Id = result.Id;
                                string Imagepath = data.Result;
                                var editFileData = await EditImageFile(imageFile, Id, Imagepath);
                                await _apiRepository.MakeApiCallAsync("api/Admin/UpdateImage", HttpMethod.Post, editFileData);
                            }

                        }
                    }
                }

                return solutionData;
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }


        [HttpGet]
        public async Task<string> GetSolutionsList()
        {
            var serviceList = await _apiRepository.MakeApiCallAsync("api/Admin/SolutionList", HttpMethod.Get);
            // Set the BlobStorageBaseUrl property for each service and generate the SAS token

            dynamic data = JsonConvert.DeserializeObject(serviceList);
            // var result = JsonConvert.DeserializeObject<SolutionsModel>(serviceList);

            try
            {
                if (data.Result != null)
                {
                    foreach (var service in data.Result)
                    {
                        string imagepath = service.ImagePath;
                        string sasToken = GenerateSasToken(imagepath);
                        string imageUrlWithSas = $"{service.ImagePath}?{sasToken}";
                        service.ImageUrlWithSas = imageUrlWithSas;

                    }

                }

            }
            catch (Exception ex)
            {
                return ex.Message + ex.InnerException;
            }
            string jsonString = JsonConvert.SerializeObject(data, Formatting.Indented);
            return jsonString;
        }


        [HttpPost]
        public async Task<string> DeleteSolutions([FromBody] SolutionIdModel solutionsModel)
        {
            try
            {
                if (solutionsModel != null)
                {
                    // Get the Azure Blob Storage connection string from configuration
                    var connectionString = _configuration.GetConnectionString("AzureBlobStorage");

                    if (!string.IsNullOrEmpty(solutionsModel.ImagePath))
                    {
                        BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
                        BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("profileimages");

                        // Ensure that the image path contains only the blob name without the container URL
                        string blobName = Path.GetFileName(solutionsModel.ImagePath);

                        BlobClient blobClient = containerClient.GetBlobClient(blobName);

                        await blobClient.DeleteIfExistsAsync();
                    }


                    var serviceData = await _apiRepository.MakeApiCallAsync("api/Admin/DeleteSolutionById", HttpMethod.Post, solutionsModel);
                    return serviceData;
                }
                else
                {
                    return "failed to receive data..";
                }
            }
            catch (Exception ex)
            {

            }
            return "";

        }

        [HttpGet]
        public async Task<string> GetFreelancers()
        {
            var userList = await _apiRepository.MakeApiCallAsync("api/Admin/getFreelancerByLevel", HttpMethod.Get);
            return userList;
        }

        [HttpPost]
        public async Task<string> GetSolutiondataById([FromBody] SolutionIdModel solutionsModel)
        {
            var serviceList = await _apiRepository.MakeApiCallAsync("api/Admin/SolutionDataById", HttpMethod.Post, solutionsModel);

            string imageUrlWithSas = string.Empty;
            dynamic data = JsonConvert.DeserializeObject(serviceList);
            try
            {
                if (data["StatusCode"] == 200)
                {
                    string imagepath = data.Result.Solution.ImagePath;
                    string sasToken = GenerateSasToken(imagepath);
                    imageUrlWithSas = $"{data.Result.Solution.ImagePath}?{sasToken}";
                    data.Result.Solution.ImageUrlWithSas = imageUrlWithSas;
                }
            }
            catch (Exception ex)
            {
                return ex.Message + ex.InnerException;
            }
            string convertjsonTostring = JsonConvert.SerializeObject(data, Formatting.Indented);
            return convertjsonTostring;
        }

        private static string GetEndpointSuffixFromConnectionString(string connectionString)
        {
            string[] parts = connectionString.Split(";");
            foreach (var part in parts)
            {
                string[] subparts = part.Split("=");
                if (subparts.Length == 2 && subparts[0].Equals("EndpointSuffix"))
                {
                    return subparts[1];
                }
            }
            return null;
        }

        private string GenerateSasToken(string imageUrl)
        {
            // Get the blob container name and blob name from the image URL
            string blobName = Path.GetFileName(imageUrl);

            // Create a shared access policy that allows read access to the blob
            BlobSasBuilder sasBuilder = new BlobSasBuilder()
            {
                BlobContainerName = ContainerName,
                BlobName = blobName,
                Resource = "b",
                StartsOn = DateTime.UtcNow.AddMinutes(-5), // Adjust the start time if needed
                ExpiresOn = DateTime.UtcNow.AddMinutes(10), // Adjust the expiry time if needed,
                Protocol = SasProtocol.Https
            };
            sasBuilder.SetPermissions(BlobSasPermissions.Read);

            // Get the Azure Blob Storage connection string from configuration
            var connectionString = _configuration.GetConnectionString("AzureBlobStorage");

            // Extract the AccountName and AccountKey from the connection string
            var accountName = GetAccountNameFromConnectionString(connectionString);
            var accountKey = GetAccountKeyFromConnectionString(connectionString);

            // Create a StorageSharedKeyCredential using the AccountName and AccountKey
            StorageSharedKeyCredential credential = new StorageSharedKeyCredential(accountName, accountKey);

            // Generate the SAS token
            string sasToken = sasBuilder.ToSasQueryParameters(credential).ToString();

            return sasToken;
        }


        private string GetAccountNameFromConnectionString(string connectionString)
        {
            try
            {
                var accountNameStartIndex = connectionString.IndexOf("AccountName=", StringComparison.InvariantCultureIgnoreCase) + "AccountName=".Length;
                var accountNameEndIndex = connectionString.IndexOf(";", accountNameStartIndex, StringComparison.InvariantCultureIgnoreCase);
                var accountNameLength = accountNameEndIndex - accountNameStartIndex;
                return connectionString.Substring(accountNameStartIndex, accountNameLength);
            }
            catch (Exception ex)
            {

Aephy.WEB.Admin/Views/Solutions/Solution.cshtml
<main id="main" class="main">
    <div class="row">
        <!-- Recent Sales -->
        <div class="col-12">
            <div class="card recent-sales overflow-auto">

                <div class="card-body">
                    <h5 class="card-title">Solutions</h5>

                    <a class="btn btn-brand m-2" onclick="OpenAddIndustriesModalPopup();">Create Solution</a>

                    <table class="table table-borderless datatable" id="solutionList">
                        <thead>
                            <tr>
                                <th style="width:10%">Id</th>
                                <th style="width:10%">Title</th>
                                <th style="width:10%">Sub Title</th>
                                <th style="width:30%">Description</th>
                                <th style="width:20%">Image</th>
                                <th style="width:10%">Services</th>
                                <th style="width:10%">Industries</th>
                                <th style="width:10%"></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div><!-- End Recent Sales -->
    </div>


</main>
<script>
    $(function () {
        GetSolutionList()
    });
    function GetSolutionList() {
        $.ajax({
            type: "Get",
            url: "@Url.Action("GetSolutionsList", "Solutions")",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                $('#solutionList').DataTable({
                    destroy: true,
                    data: result.Result,
                    "columns": [
                        {
                            "data": "Id",
                            "render": function (data, type, row) {
                                return '<a class="cls-service" onclick=GetSolutionDataById(' + data + ')>' + data + '</a>';
                            }
                        },
                        { "data": "Title" },
                        { "data": "SubTitle" },
                        {
                            "data": "Description",
                            "render": function (data, type, row) {
                                var description = data.length > 35 ? data.substring(0, 35) + "..." : data;
                                return "<span title='" + data + "'>" + description + "</span>";
                            }
                        },
                        {
                            "data": "ImageUrlWithSas",
                            "render": function (data, type, row) {
                                return '<img src="' + data + '" alt="Image" height="70" width="150" />';
                            }
                        },
                        { "data": "Services" },
                        { "data": "Industries" },
                        {
                            "data": "Id",
                            "render": function (data, type, row) {
                                return '<a class="btn btn-danger btn-sm" style="color: white;" onclick=DeleteSolution("' + row.ImageUrlWithSas + '","' + row.ImagePath + '",' + row.Id + ')>Delete</a>';

                            }
                        }

                    ]
                });


            },
            error: function (result) {
                alert("failure");
            }
        });
    }
    function DeleteSolution(ImageUrlWithSas, ImagePath, Id) {

        if (confirm('Are you sure want to delete solution?')) {
            var ServiceData = {
                Id: Id,
                ImagePath: ImagePath,
                ImageUrlWithSas: ImageUrlWithSas

            };
            $.ajax({
                type: "POST",
                url: "@Url.Action("DeleteSolutions", "Solutions")",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify(ServiceData),
                success: function (result) {
                    alert(result.Message);
                    GetSolutionList();

                },
                error: function (result) {
                    alert("Error occured..");
                }
            });
        }
    }

    function OpenAddIndustriesModalPopup() {
        $("#addSolutionModal").modal('show')
    }

    function GetSolutionDataById(Id) {
        var ServiceData = {
            Id: Id,
        };
        $.ajax({
            type: "POST",
            url: "@Url.Action("GetSolutiondataById", "Solutions")",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: JSON.stringify(ServiceData),
            success: function (result) {
                if (result != null) {
                    $("#addSolutionModal").modal('show')
                    $("#solution-img").remove()
                    $("#SolutionId").val(result.Result.Solution.Id)
                    $("#SolutionTitle").val(result.Result.Solution.Title)
                    $("#Solution_SubTitle").val(result.Result.Solution.SubTitle)
                    $("#SolutionDescription").val(result.Result.Solution.Description)
                    $("#ImagePath").val(result.Result.Solution.ImagePath)
                    $("#solutionImagepreview").find("span").first().remove();
                    $('#solutionImagepreview').show();
                    var span = document.createElement('span');
                    span.innerHTML =
                        ['<img class="SolutionImage" src="', result.Result.Solution.ImageUrlWithSas, '" style="height:200px;width:200px;"/>']
                            .join('');
                    document.getElementById('solutionImagepreview').insertBefore(span, null);
                    var industryvalues = new Array();
                    var servicesvalues = new Array();

                    $.each(result.Result.IndustryResult, function (index, value) {
                        industryvalues.push(value.IndustryId)
                    });

                    $.each(result.Result.ServiceResult, function (index, value) {
                        servicesvalues.push(value.ServicesId)
                    });
                    $('#drp-services').val(servicesvalues).trigger('chosen:updated');
                    $('#drp-industries').val(industryvalues).trigger('chosen:updated');
                }

            },
            error: function (result) {
                alert("Error occured..");
            }
        });
    }

</script>