Aephy.WEB.Admin/Controllers/GeneralSettingsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Aephy.WEB.Provider;
using Aephy.WEB.Models;

namespace Aephy.WEB.Admin.Controllers
{
    public class GeneralSettingsController : Controller
    {
        private readonly IApiRepository _apiRepository;
        private readonly string _rootPath;
        private readonly IConfiguration _configuration;
        private readonly string _connectionString;

        public GeneralSettingsController(IApiRepository apiRepository, IWebHostEnvironment hostEnvironment, IConfiguration configuration)
        {
            _apiRepository = apiRepository;
            _configuration = configuration;
            _rootPath = hostEnvironment.WebRootPath;
            _connectionString = "DefaultEndpointsProtocol=https;AccountName=aephystorageaccount;AccountKey=nEy6xh4P4m2d94iDgqq+yNB99bucjGMD1wp2L6sbsNFjHPaUQiCHgc5b4hmBmeRtYsiA/WvudVmV+AStwz3djw==;EndpointSuffix=core.windows.net";
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Settings()
        {
            return View();
        }

        [HttpPost]
        public async Task<string> SaveLevelData(string FormData)
        {
            var LevelDataList = JsonConvert.DeserializeObject<List<LevelRange>>(FormData);
            try
            {
                    var Response = await _apiRepository.MakeApiCallAsync("api/Admin/SaveLevelData", HttpMethod.Post, LevelDataList);
                    return Response;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return "";
        }

        [HttpGet]
        public async Task<string> getSavedLevelsdata()
        {
            try
            {
                var Response = await _apiRepository.MakeApiCallAsync("api/Admin/GetSavedLevelsList", HttpMethod.Get);
                return Response;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return "";
        }

    }
}

Aephy.WEB.Admin/Views/GeneralSettings/Settings.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "- Settings";
}

<style>
    .GigLevels-card .title {
        margin:20px 0;
    }

        .GigLevels-card .title h5 {
        font-weight:700;
    }

    .required-error{
        display:none;
    }

</style>

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Settings</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/Home/Index">Dashboard</a></li>
                <li class="breadcrumb-item active">Settings</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <!-- Left side columns -->
            <div class="col-lg-8">
                <div class="row">
                    <!-- Recent Sales -->
                    <div class="col-12">
                        <div class="card GigLevels-card overflow-auto">

                            <div class="card-body">
                                <div class="row mb-3 title d-flex justify-content-center">
                                    <h5 for="minLevel" class="col-md-4 col-lg-5 col-form-label">Level</h5>
                                    <div class="col-3">
                                        <h5 for="minLevel" class="col-form-label">Min</h5>
                                    </div>
                                    <div class="col-3">
                                        <h5 for="maxLevel" class="col-form-label">Max</h5>
                                    </div>
                                </div>
                                <form name="SaveLevelsForm" id="FormSaveLevels">
                                    <div class="row mb-3 d-flex justify-content-center">
                                        <label for="minLevel" class="col-md-4 col-lg-5 col-form-label">Associate [EUR]</label>
                                        <input name="LevelID" type="text" class="form-control d-none" value="0">
                                        <div class="col-3">
                                            <input name="minLevel" id="minLevel1" type="text" class="form-control">
                                            <label class="error required-error">This field is required.</label>
                                        </div>
                                        <div class="col-3">
                                            <input name="maxLevel" id="maxLevel1" type="text" class="form-control">
                                            <label class="error required-error">This field is required.</label>
                                        </div>
                                    </div>

                                    <div class="row mb-3 d-flex justify-content-center">
                                        <label for="minLevel" class="col-md-4 col-lg-5 col-form-label">Expert [EUR]</label>
                                        <input name="LevelID" type="text" class="form-control d-none" value="0">
                                        <div class="col-3">
                                            <input name="minLevel" id="minLevel1" type="text" class="form-control">
                                            <label class="error required-error">This field is required.</label>
                                        </div>
                                        <div class="col-3">
                                            <input name="maxLevel" id="maxLevel1" type="text" class="form-control">
                                            <label class="error required-error">This field is required.</label>
                                        </div>
                                    </div>

                                    <div class="row mb-3 d-flex justify-content-center">
                                        <label for="minLevel" class="col-md-4 col-lg-5 col-form-label">Project Manager [EUR]</label>
                                        <input name="LevelID" type="text" class="form-control d-none" value="0">
                                        <div class="col-3">
                                            <input name="minLevel" id="minLevel1" type="text" class="form-control">
                                            <label class="error required-error">This field is required.</label>
                                        </div>
                                        <div class="col-3">
                                            <input name="maxLevel" id="maxLevel1" type="text" class="form-control">
                                            <label class="error required-error">This field is required.</label>
                                        </div>
                                    </div>

                                   @* <div class="row mb-3 d-flex justify-content-center">
                                        <label for="minLevel" class="col-md-4 col-lg-5 col-form-label">Project Manager / Project Architect</label>
                                        <input name="LevelID" type="text" class="form-control d-none" value="0">
                                        <div class="col-3">
                                            <input name="minLevel" id="minLevel1" type="text" class="form-control">
                                            <label class="error required-error">This field is required.</label>
                                        </div>
                                        <div class="col-3">
                                            <input name="maxLevel" id="maxLevel1" type="text" class="form-control">
                                            <label class="error required-error">This field is required.</label>
                                        </div>
                                    </div>*@

                                    <div class="text-end">
                                        <button type="submit" class="btn btn-primary px-4">Save</button>
                                    </div>
                                </form><!-- End Change Password Form -->
                            </div>

                        </div>
                    </div><!-- End Recent Sales -->
                </div>
            </div><!-- End Left side columns -->
        </div>
    </section>

</main><!-- End #main -->
<script type="text/javascript">

    $(function () {
        bindLevelsRangeData();
        $("form[name='SaveLevelsForm']").validate({
            submitHandler: function (form) {
                SaveLevelsData()
            }
        });
    });

    function SaveLevelsData(){

        var ArrayLevelID = new Array();
        var ArrayminLevel = new Array();
        var ArraymaxLevel = new Array();
        var ArrayLevel = ["Associate", "Expert", "Project Manager", "Project Manager / Project Architect"];
        var ids = '';
        var errorCount = 0;

        $("input:text[name=LevelID]").each(function () {
            ArrayLevelID.push($(this).val());
        });

        $("input:text[name=minLevel]").each(function () {
            if($(this).val() == ''){
                errorCount++;
                var errorLabel = $(this).parent().find('.required-error');
                errorLabel.text('This field is required.');
                errorLabel.css('display', 'inline-block');
            }
            ArrayminLevel.push($(this).val()); 
        });

        $("input:text[name=maxLevel]").each(function () {
            if ($(this).val() == '') {
                errorCount++;
                var errorLabel = $(this).parent().find('.required-error');
                errorLabel.text('This field is required.');
                errorLabel.css('display', 'inline-block');
            }
            ArraymaxLevel.push($(this).val());
        });

        if (errorCount == 0) {
        var listSize = ArrayLevelID.length;
        if (listSize > 0){
            var index = 0;
            var dataList = [];
            var flag = 0;
            for(index = 0; index < listSize; index++){
                var minval = parseFloat(ArrayminLevel[index]);
                var maxval = parseFloat(ArraymaxLevel[index]);
                if (minval > maxval) {
                    showToaster("error", "Error !", "Min level must be less than max level..!!");
                    flag++;
                    break;
                }
                dataList.push({
                    ID:ArrayLevelID[index],
                    Level: ArrayLevel[index],
                    minLevel:ArrayminLevel[index],
                    maxLevel:ArraymaxLevel[index]
                });
            }
            if(flag < 1){
                var formData = new FormData();
                formData.append("FormData", JSON.stringify(dataList));

                $('#preloader').show();

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("SaveLevelData", "GeneralSettings")",
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function (result) {
                        $('#preloader').hide();
                        var test = result.split(",")[1].split(":")[1]
                        showToaster("success", "Success", test.replace(/\"/g, ""));
                        bindLevelsRangeData();
                    },
                    error: function (result) {
                        $('#preloader').hide();
                            showToaster("error", "Error !", result.responseText);
                        bindLevelsRangeData();
                    }
                });
            }
        }
        }
    }

    function bindLevelsRangeData(){
        $('#preloader').show();
        $.ajax({
            type: "GET",
            url: "@Url.Action("getSavedLevelsdata", "GeneralSettings")",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                var size = result.Result.length;
                var res = 0;
                var htm = '';
                if(size > 0){
                    for(res = 0; res < size; res++){
                        var item = result.Result[res];
                        if (item.Level != "Project Manager / Project Architect"){
                            var level = res + 1;
                            htm += '<div class="row mb-3 d-flex justify-content-center">';
                            htm += '<label class= "col-md-4 col-lg-5 col-form-label">' + item.Level + ' [EUR]</label>';
                            htm += '<input name = "LevelID" type = "text" class="form-control d-none" value = "' + item.ID + '" id = "architect_LevelID">';
                            htm += '<div class="col-3">';
                            htm += '<input name="minLevel" id="minLevel' + level + '" type = "text" class="form-control" value="' + item.minLevel + '" id = "architect_minLevel">';
                            htm += '<label class="error required-error">This field is required.</label>';
                            htm += '</div>';
                            htm += '<div class="col-3">';
                            htm += '<input name="maxLevel"  id="maxLevel' + level + '" type = "text" class="form-control" value="' + item.maxLevel + '" id = "architect_maxLevel">';
                            htm += '<label class="error required-error">This field is required.</label>';
                            htm += '</div>';
                            htm += '</div>';
                        }
                       
                    }
                    htm += '<div class="text-end">';
                    htm += '<button type="submit" class="btn btn-primary px-4"> Save </button>';
                    htm += '</div>';
                    $('#FormSaveLevels').html('');
                    //$('#FormSaveLevels').find('div').remove();
                    $('#FormSaveLevels').append(htm);
                }
                $('#preloader').hide();
            },
            error: function (result) {
                $('#preloader').hide();
                showToaster("error", "Error !", "Failure");
            }
        });
    }
</script>